/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.okulmvn.Gui;

import com.okulmvn.Dal.tblbolumDAO;
import com.okulmvn.Models.tblbolum;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cesur
 */


public class frmBolum extends javax.swing.JFrame {

    public static int secilenid;
    public static int tblsecilen;
    List<tblbolum> bolumliste=new ArrayList<tblbolum>();
    tblbolumDAO db= new tblbolumDAO();
   
    /**
     * Creates new form frmBolum
     */
    public frmBolum() {
        initComponents();
       
         bolumliste=db.listele(new tblbolum());
           tablodoldur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuduzenle = new javax.swing.JMenuItem();
        menusil = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtalanadi = new javax.swing.JTextField();
        btnyenikayit = new javax.swing.JButton();
        btnkaydet = new javax.swing.JButton();
        btnguncelle = new javax.swing.JButton();
        btniptal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBolum = new javax.swing.JTable();

        menuduzenle.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesur\\Desktop\\güncelle.png")); // NOI18N
        menuduzenle.setText("menuduzenle");
        menuduzenle.setToolTipText("");
        menuduzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuduzenleActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuduzenle);

        menusil.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesur\\Desktop\\iptal.png")); // NOI18N
        menusil.setText("menusil");
        menusil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusilActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menusil);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bölüm");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 59, 120, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 10, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 53, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 100));

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Alan Adı");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        txtalanadi.setEditable(false);
        txtalanadi.setBackground(new java.awt.Color(108, 122, 137));
        txtalanadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalanadiActionPerformed(evt);
            }
        });
        jPanel2.add(txtalanadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 157, -1));

        btnyenikayit.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesur\\Desktop\\yeni kayit.png")); // NOI18N
        btnyenikayit.setText("Yeni Kayıt");
        btnyenikayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyenikayitActionPerformed(evt);
            }
        });
        jPanel2.add(btnyenikayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, 50));

        btnkaydet.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesur\\Desktop\\kayit.png")); // NOI18N
        btnkaydet.setText("Kaydet");
        btnkaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaydetActionPerformed(evt);
            }
        });
        jPanel2.add(btnkaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 120, 50));

        btnguncelle.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesur\\Desktop\\güncelle.png")); // NOI18N
        btnguncelle.setText("Güncelle");
        btnguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguncelleActionPerformed(evt);
            }
        });
        jPanel2.add(btnguncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 120, 50));

        btniptal.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesur\\Desktop\\iptal.png")); // NOI18N
        btniptal.setText("İptal");
        btniptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniptalActionPerformed(evt);
            }
        });
        jPanel2.add(btniptal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 120, 50));

        tblBolum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "BölümID", "Bölüm Adı"
            }
        ));
        tblBolum.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tblBolum);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 213, 580, 190));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 770, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnyenikayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyenikayitActionPerformed
       btnyenikayit.setEnabled(false);
       btnkaydet.setEnabled(true);
       btniptal.setEnabled(true);
       txtac();
    }//GEN-LAST:event_btnyenikayitActionPerformed

    private void btnkaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaydetActionPerformed
          if(txtalanadi.getText().equals(""))
          {
              
              JOptionPane.showMessageDialog(null,"Lütfen Boş alanları doldurunuz");
              
              
              
          }
          else
          {
              tblbolum tbl= new tblbolum();
                 tbl.setAlan(txtalanadi.getText());
                 bolumliste.add(tbl);
                 tbl.setSilid(1);
                 db.kaydet(tbl);
                 tablodoldur();
                 temizle();
                  btnyenikayit.setEnabled(true);
                  btnkaydet.setEnabled(false);
                  btniptal.setEnabled(false);
                   
                 
                 
              
              
              
          }
    }//GEN-LAST:event_btnkaydetActionPerformed

    private void menusilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusilActionPerformed
       int reply = JOptionPane.showConfirmDialog(null, "İlgili Kaydı silmek istiyor musunuz?",
              "UYARI", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            
        int secilen = tblBolum.getSelectedRow();
        int id=Integer.parseInt(tblBolum.getValueAt(secilen, 0).toString());
        satirsil(secilen);
        db.sil(id);
        tablodoldur();
        
        }
        else {
           JOptionPane.showMessageDialog(null, "İşlem İptal Edilmiştir.");
           
        }
    
    }//GEN-LAST:event_menusilActionPerformed
  public void satirsil (int id)
  {
      
      try {
         bolumliste.remove(id);
         
         
        
        
         
         JOptionPane.showMessageDialog(null, "Kaydınız başarıyla silinmiştir");
          
      } catch (Exception e) {
          
          JOptionPane.showMessageDialog(null, "HATA!! Boş kayıt Silme İşlemi Yapamazsınız.");
      }
      
      
  }
    private void menuduzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuduzenleActionPerformed
       int secilen= tblBolum.getSelectedRow();
      tblsecilen=secilen;
        secilenid =Integer.parseInt(tblBolum.getValueAt(secilen, 0).toString());
        txtalanadi.setText(tblBolum.getValueAt(secilen, 1).toString());
    }//GEN-LAST:event_menuduzenleActionPerformed

    private void btniptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniptalActionPerformed
        temizle();
        btnyenikayit.setEnabled(true);
       btnkaydet.setEnabled(false);
        btnguncelle.setEnabled(false);
        btniptal.setEnabled(false);
    }//GEN-LAST:event_btniptalActionPerformed

    private void btnguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguncelleActionPerformed
       tblbolum tbl= new tblbolum();
       tbl.setAlan(txtalanadi.getText());
       tbl.setId(secilenid);
       bolumliste.set(tblsecilen, tbl);
       db.duzenle(tbl);
       tablodoldur();
       temizle();
        btnyenikayit.setEnabled(true);
        btnguncelle.setEnabled(false);
        btniptal.setEnabled(false);
       
    }//GEN-LAST:event_btnguncelleActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtalanadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalanadiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalanadiActionPerformed
  public void satirekle()
  {
      
      DefaultTableModel dt= (DefaultTableModel)this.tblBolum.getModel();
        dt.setRowCount(dt.getRowCount()+1);
        this.tblBolum.repaint();
      
  }
  public void txtac()
  {
      
      txtalanadi.setEditable(true);
      txtalanadi.setBackground(new java.awt.Color(255, 255, 255));
      
      
  }
     public void tablodoldur()
     {
         int i=0;
         tablotemizle();
         for (tblbolum mst : bolumliste) {
             satirekle();
             tblBolum.setValueAt(mst.getId(), 0+i, 0);
             tblBolum.setValueAt(mst.getAlan(), 0+i, 1);
             
             
             i++;
             
             
             
          
             
             
             
             
         }
         
         
     }
     public void tablotemizle()
     {
         DefaultTableModel df=(DefaultTableModel)this.tblBolum.getModel();
         df.getDataVector().removeAllElements();
     }
     public void temizle()
             
     {
        
         txtalanadi.setText("");
         
         
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBolum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguncelle;
    private javax.swing.JButton btniptal;
    private javax.swing.JButton btnkaydet;
    private javax.swing.JButton btnyenikayit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuduzenle;
    private javax.swing.JMenuItem menusil;
    private javax.swing.JTable tblBolum;
    private javax.swing.JTextField txtalanadi;
    // End of variables declaration//GEN-END:variables
}
