/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.okulmvn.Gui;

import com.okulmvn.Dal.tblsinifDAO;
import com.okulmvn.Dal.tbogrenciDAO;
import com.okulmvn.Models.tblogrenci;
import com.okulmvn.Models.tblsinif;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cesur
 */
public class frmYoklama extends javax.swing.JFrame {

    /**
     * Creates new form frmYoklama
     */
     List<tblsinif> listesinif = new ArrayList<>();
    List<tblogrenci> liste = new ArrayList<>();
    tblsinifDAO ds= new tblsinifDAO();
    tbogrenciDAO da= new tbogrenciDAO();
    
    public frmYoklama() {
        
        initComponents();
        combobaxcekme();
    }
public void combobaxcekme()
{
    
    for (tblsinif item : ds.listele(new tblsinif())) {
        
        cmbsinifcek.addItem(item.getSinifadi());
        
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbsinifcek = new javax.swing.JComboBox<>();
        btnyoklamakayit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableyoklama = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("YOKLAMA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("-");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 70));

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbsinifcek.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbsinifcekİtemStateChanged(evt);
            }
        });
        jPanel2.add(cmbsinifcek, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 30));

        btnyoklamakayit.setText("KAYDET");
        btnyoklamakayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyoklamakayitActionPerformed(evt);
            }
        });
        jPanel2.add(btnyoklamakayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, 50));

        jtableyoklama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtableyoklama);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 820, 420));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1080, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbsinifcekİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbsinifcekİtemStateChanged
          int id = cmbsinifcek.getSelectedIndex();
          int dbid = (int)ds.listele(new tblsinif()).get(id).getId();
        List<tblogrenci> ls= new ArrayList<>();
        for (tblogrenci ogr : da.listele(new tblogrenci())) {
            if(ogr.getSinifid()==dbid){
                ls.add(ogr);
                System.err.println("db id..:"+ ogr.getSinifid());
                System.err.println(" id..:"+ dbid);
                
            }
            System.err.println(" id..:"+ dbid);
                
        }
        Verilerigir(ds.listele(new tblsinif()).get(id), ls);
    }//GEN-LAST:event_cmbsinifcekİtemStateChanged

    private void btnyoklamakayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyoklamakayitActionPerformed
        
    }//GEN-LAST:event_btnyoklamakayitActionPerformed
public void Verilerigir(tblsinif sinif, List<tblogrenci> ogrenciler){
    
        Object[][] satirlistesi = new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            };
         String[] basliklar = new String[sinif.getDerssaati()+3];
        basliklar[0] = "ADI";
        basliklar[1] = "SOYADI";
        basliklar[2] = "NUMARASI";
         Class[] types = new Class [sinif.getDerssaati()+3];
         types[0] =  java.lang.Object.class;
         types[1] =  java.lang.Object.class;
         types[2] =  java.lang.Object.class;
         
      
        for (int i = 1; i <= sinif.getDerssaati(); i++) {
            basliklar[2+i] = i+". Ders";
            types[2+i] = java.lang.Boolean.class;
        }
        
        tabloCiz(satirlistesi, basliklar, types);
        int i=0;
        for (tblogrenci ogr : ogrenciler) {
            satirekle();
              jtableyoklama.setValueAt(ogr.getAd(), i, 0);
              jtableyoklama.setValueAt(ogr.getSoyadi(), i, 1);
              jtableyoklama.setValueAt(ogr.getNumara(), i, 2);
           i++;
              
        }
      
        
    }

  public void satirekle()
  {
      
       DefaultTableModel dt= (DefaultTableModel)this.jtableyoklama.getModel();
        dt.setRowCount(dt.getRowCount()+1);
        this.jtableyoklama.repaint();
  }
public void tabloCiz(Object[][] satir, String[] basliklar, Class[] ColonDegerleri){
    
     jtableyoklama.setModel(new javax.swing.table.DefaultTableModel(
           satir,
            basliklar
        ) {
            Class[] types = ColonDegerleri;

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmYoklama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmYoklama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmYoklama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmYoklama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmYoklama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnyoklamakayit;
    private javax.swing.JComboBox<String> cmbsinifcek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableyoklama;
    // End of variables declaration//GEN-END:variables
}
