/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.okulmvn.Gui;

import com.okulmvn.Dal.tblyetkiDAO;
import com.okulmvn.Models.tblkullanici;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author cesur
 */
public class frmYetki extends javax.swing.JFrame {

    /**
     * Creates new form frmYetki
     */
    public static int secilenid;
    public static int tblsecilen;
    List<tblkullanici> kullaniciliste= new ArrayList<tblkullanici>();
    tblyetkiDAO db= new tblyetkiDAO();
    public frmYetki() {
        initComponents();
        kullaniciliste=db.listele(new tblkullanici());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsoyad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdogumtarihi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtveliadi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtdevamsizlik = new javax.swing.JTextField();
        txtvelisoaydi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtvelitel = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtadres = new javax.swing.JTextArea();
        btnyenikayit1 = new javax.swing.JButton();
        btnkaydet1 = new javax.swing.JButton();
        btnguncelle1 = new javax.swing.JButton();
        btniptal1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtNumara = new javax.swing.JTextField();
        cmbbolum = new javax.swing.JComboBox<>();
        cmbsinif = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jlabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmbkangrubu = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txttc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        txttelefon = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtkullaniciadi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtsifre = new javax.swing.JTextField();
        btniptal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbyetki = new javax.swing.JComboBox<>();
        btnyenikayit = new javax.swing.JButton();
        btnkaydet = new javax.swing.JButton();
        btnguncelle = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("YETKİ İŞLEMLERİ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 58, -1, -1));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Adı");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        txtad.setEditable(false);
        txtad.setBackground(new java.awt.Color(108, 122, 137));
        txtad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadActionPerformed(evt);
            }
        });
        jPanel3.add(txtad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Soyadı");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtsoyad.setEditable(false);
        txtsoyad.setBackground(new java.awt.Color(108, 122, 137));
        jPanel3.add(txtsoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText("Numara");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        txtdogumtarihi.setEditable(false);
        txtdogumtarihi.setBackground(new java.awt.Color(108, 122, 137));
        jPanel3.add(txtdogumtarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Sınıfı");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setText("Telefon");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setText("Veli Adı");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 51, -1));

        txtveliadi.setEditable(false);
        txtveliadi.setBackground(new java.awt.Color(108, 122, 137));
        txtveliadi.setToolTipText("");
        txtveliadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtveliadiActionPerformed(evt);
            }
        });
        jPanel3.add(txtveliadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 170, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 240, 241));
        jLabel11.setText("Veli Soyadı");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 95, -1));

        txtdevamsizlik.setEditable(false);
        txtdevamsizlik.setBackground(new java.awt.Color(108, 122, 137));
        jPanel3.add(txtdevamsizlik, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 170, -1));

        txtvelisoaydi.setEditable(false);
        txtvelisoaydi.setBackground(new java.awt.Color(108, 122, 137));
        txtvelisoaydi.setToolTipText("");
        txtvelisoaydi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvelisoaydiActionPerformed(evt);
            }
        });
        jPanel3.add(txtvelisoaydi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 170, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(236, 240, 241));
        jLabel12.setText("Veli Telefonu");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 95, -1));

        txtvelitel.setEditable(false);
        txtvelitel.setBackground(new java.awt.Color(108, 122, 137));
        txtvelitel.setToolTipText("");
        txtvelitel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvelitelActionPerformed(evt);
            }
        });
        jPanel3.add(txtvelitel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 170, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(236, 240, 241));
        jLabel13.setText("Devamsızlık");
        jLabel13.setToolTipText("");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(236, 240, 241));
        jLabel14.setText("Bölüm");
        jLabel14.setToolTipText("");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(236, 240, 241));
        jLabel16.setText("Adres");
        jLabel16.setToolTipText("");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 80, -1));

        txtadres.setEditable(false);
        txtadres.setBackground(new java.awt.Color(108, 122, 137));
        txtadres.setColumns(20);
        txtadres.setRows(5);
        jScrollPane2.setViewportView(txtadres);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 170, 80));

        btnyenikayit1.setBackground(new java.awt.Color(236, 240, 241));
        btnyenikayit1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesur\\Desktop\\yeni kayit.png")); // NOI18N
        btnyenikayit1.setText("Yeni Kayıt");
        btnyenikayit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyenikayit1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnyenikayit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 120, 50));

        btnkaydet1.setBackground(new java.awt.Color(236, 240, 241));
        btnkaydet1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesur\\Desktop\\kayit.png")); // NOI18N
        btnkaydet1.setText("Kaydet");
        btnkaydet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaydet1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnkaydet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 107, 50));

        btnguncelle1.setBackground(new java.awt.Color(236, 240, 241));
        btnguncelle1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesur\\Desktop\\güncelle.png")); // NOI18N
        btnguncelle1.setText("Güncelle");
        btnguncelle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguncelle1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnguncelle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 120, 50));

        btniptal1.setBackground(new java.awt.Color(236, 240, 241));
        btniptal1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesur\\Desktop\\iptal.png")); // NOI18N
        btniptal1.setText("İptal");
        jPanel3.add(btniptal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 107, 50));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(236, 240, 241));
        jLabel17.setText("Tc");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        txtNumara.setEditable(false);
        txtNumara.setBackground(new java.awt.Color(108, 122, 137));
        txtNumara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumaraKeyTyped(evt);
            }
        });
        jPanel3.add(txtNumara, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 170, -1));

        jPanel3.add(cmbbolum, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 170, -1));

        cmbsinif.setBackground(new java.awt.Color(108, 122, 137));
        jPanel3.add(cmbsinif, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 170, -1));

        jButton5.setText("Resim Yükle");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 120, 50));

        jlabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 180, 190));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(236, 240, 241));
        jLabel19.setText("Kan Grubu");
        jLabel19.setToolTipText("");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(236, 240, 241));
        jLabel20.setText("Cinsiyet");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, 20));

        cmbkangrubu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O Rh+", "O Rh-", "A Rh+", "A Rh-" }));
        jPanel3.add(cmbkangrubu, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 170, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(236, 240, 241));
        jLabel21.setText("Email");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        txtemail.setEditable(false);
        txtemail.setBackground(new java.awt.Color(108, 122, 137));
        jPanel3.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 170, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(236, 240, 241));
        jLabel15.setText("Doğum Tarihi");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        txttc.setEditable(false);
        txttc.setBackground(new java.awt.Color(108, 122, 137));
        txttc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttcKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttcKeyTyped(evt);
            }
        });
        jPanel3.add(txttc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 170, -1));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Adı", "Soyadı", "Numara", "Sınıfı"
            }
        ));
        jScrollPane1.setViewportView(jTable5);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 640, 90));

        txttelefon.setEditable(false);
        txttelefon.setBackground(new java.awt.Color(108, 122, 137));
        txttelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonActionPerformed(evt);
            }
        });
        jPanel3.add(txttelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 170, -1));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton1.setText("Erkek");
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButton2.setText("Bayan");
        jPanel3.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 990, 600));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("X");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jLabel18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel18KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("-");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("-");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("X");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 100));

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setText("Kullanıcı Adı");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        txtkullaniciadi.setEditable(false);
        txtkullaniciadi.setBackground(new java.awt.Color(108, 122, 137));
        jPanel2.add(txtkullaniciadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 138, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("Şifre");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        txtsifre.setEditable(false);
        txtsifre.setBackground(new java.awt.Color(108, 122, 137));
        jPanel2.add(txtsifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 138, -1));

        btniptal.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesur\\Desktop\\iptal.png")); // NOI18N
        btniptal.setText("İptal");
        btniptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniptalActionPerformed(evt);
            }
        });
        jPanel2.add(btniptal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 110, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Yetki Tipi");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        cmbyetki.setBackground(new java.awt.Color(108, 122, 137));
        cmbyetki.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cmbyetki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbyetkiActionPerformed(evt);
            }
        });
        jPanel2.add(cmbyetki, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 140, -1));

        btnyenikayit.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesur\\Desktop\\yeni kayit.png")); // NOI18N
        btnyenikayit.setText("Yeni Kayıt");
        btnyenikayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyenikayitActionPerformed(evt);
            }
        });
        jPanel2.add(btnyenikayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 120, 50));

        btnkaydet.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesur\\Desktop\\kayit.png")); // NOI18N
        btnkaydet.setText("KAYDET");
        btnkaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaydetActionPerformed(evt);
            }
        });
        jPanel2.add(btnkaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 110, 50));

        btnguncelle.setIcon(new javax.swing.ImageIcon("C:\\Users\\cesur\\Desktop\\güncelle.png")); // NOI18N
        btnguncelle.setText("Güncelle");
        btnguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguncelleActionPerformed(evt);
            }
        });
        jPanel2.add(btnguncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 110, 50));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("-");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("X");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 100, 710, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btniptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniptalActionPerformed
      
      
      
        
    }//GEN-LAST:event_btniptalActionPerformed

    private void cmbyetkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbyetkiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbyetkiActionPerformed

    private void btnyenikayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyenikayitActionPerformed
        btnyenikayit.setEnabled(false);
           btnkaydet.setEnabled(true);
           btniptal.setEnabled(true);
           txtac();
    }//GEN-LAST:event_btnyenikayitActionPerformed
public void txtac()
{
    txtkullaniciadi.setEditable(true);
    txtsifre.setEditable(true);
    txtkullaniciadi.setBackground(new java.awt.Color(255, 255, 255));
    txtsifre.setBackground(new java.awt.Color(255, 255, 255));
    
}
    private void btnkaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaydetActionPerformed
      tblkullanici tbl= new tblkullanici();
      tbl.setKullaniciadi(txtkullaniciadi.getText());
      tbl.setSifre(txtsifre.getText());
      tbl.setKullaniciyetki(cmbyetki.getSelectedItem().toString());
      kullaniciliste.add(tbl);
      db.kaydet(tbl);
      
    }//GEN-LAST:event_btnkaydetActionPerformed

    private void btnguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguncelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguncelleActionPerformed

    private void txtadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadActionPerformed

    }//GEN-LAST:event_txtadActionPerformed

    private void txtveliadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtveliadiActionPerformed

    }//GEN-LAST:event_txtveliadiActionPerformed

    private void txtvelisoaydiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvelisoaydiActionPerformed

    }//GEN-LAST:event_txtvelisoaydiActionPerformed

    private void txtvelitelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvelitelActionPerformed

    }//GEN-LAST:event_txtvelitelActionPerformed

    private void btnyenikayit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyenikayit1ActionPerformed
        txtac();
        

    }//GEN-LAST:event_btnyenikayit1ActionPerformed

    private void btnkaydet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaydet1ActionPerformed

       

    }//GEN-LAST:event_btnkaydet1ActionPerformed

    private void btnguncelle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguncelle1ActionPerformed

    }//GEN-LAST:event_btnguncelle1ActionPerformed

    private void txtNumaraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumaraKeyTyped

  
    }//GEN-LAST:event_txtNumaraKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

     
         

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jlabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel1MouseClicked

    }//GEN-LAST:event_jlabel1MouseClicked

    private void txttcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttcKeyPressed

    }//GEN-LAST:event_txttcKeyPressed

    private void txttcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttcKeyTyped

    }//GEN-LAST:event_txttcKeyTyped

    private void txttelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
       
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel18KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel18KeyPressed

    }//GEN-LAST:event_jLabel18KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmYetki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmYetki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmYetki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmYetki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmYetki().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguncelle;
    private javax.swing.JButton btnguncelle1;
    private javax.swing.JButton btniptal;
    private javax.swing.JButton btniptal1;
    private javax.swing.JButton btnkaydet;
    private javax.swing.JButton btnkaydet1;
    private javax.swing.JButton btnyenikayit;
    private javax.swing.JButton btnyenikayit1;
    private javax.swing.JComboBox<String> cmbbolum;
    private javax.swing.JComboBox<String> cmbkangrubu;
    private javax.swing.JComboBox<String> cmbsinif;
    private javax.swing.JComboBox<String> cmbyetki;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable5;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JTextField txtNumara;
    private javax.swing.JTextField txtad;
    private javax.swing.JTextArea txtadres;
    private javax.swing.JTextField txtdevamsizlik;
    private javax.swing.JTextField txtdogumtarihi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtkullaniciadi;
    private javax.swing.JTextField txtsifre;
    private javax.swing.JTextField txtsoyad;
    private javax.swing.JTextField txttc;
    private javax.swing.JTextField txttelefon;
    private javax.swing.JTextField txtveliadi;
    private javax.swing.JTextField txtvelisoaydi;
    private javax.swing.JTextField txtvelitel;
    // End of variables declaration//GEN-END:variables
}
